git: Panic if ssh key file is not found
bors-rs/bors pull request #7
Opened 2020-08-28 19:12 UTC by jnaulty

The reading of the ssh-key-file occurs at the time git uses the
`GIT_SSH_COMMAND`, which is interpreted by a shell for `git fetch` and
`git pull`

Verification that the identity file exists should occur, and the program
should exit early if it does not exist.

Changes:
- checks ssh-key-file exists on disk as a file

Test:

- Create a file `touch test.txt`
- Update `bors.toml` value for `ssh-key-file` to be `test.txt`
- Run `rm -rf repos/ # triggers cloning of repo, when incident occurs; cargo run -- -c bors.toml serve`
- Verify `cloning <repo> to <repo-path>` in `bors` logging output
  - `[2020-08-28T19:05:44Z INFO  bors::git] cloning 'git@github.com:jnaulty/spoon-fork-bors.git' to '/home/jnaulty/github.com/bors-rs/bors/repos/jnaulty/spoon-fork-bors'`
- Update `bors.toml` value for `ssh-key-file` to be `test.txt; echo $(whoami) > /tmp/whoami.txt`
- Run `rm -f /tmp/whoami.txt; rm -rf repos/ # triggers cloning of repo, when incident occurs; cargo run -- -c bors.toml serve`
- Verify panic occurs and the file `/tmp/whoami.txt` does not exist

2020-08-28 20:07 UTC, bmwill requested changes
Just a couple things to fix and then this should be good.

2020-08-28 20:07 UTC, bmwill commented on bors/src/git.rs
> +        }
I can't comment on the line I would like to (github won't let me) but this should should be done on the fully constructed path, as that's what's actually going to be interpreted by the shell. We can also change this to be a bit cleaner and remove the unnecessary unwrap to the following:

```
if !path.is_file() {
    panic!(...);
}
```

2020-08-28 20:07 UTC, bmwill commented on bors/src/git.rs
> +    fs::metadata,
After the change is made below you can remove this.

2020-08-28 20:58 UTC, bmwill approved these changes
Perfect!

2020-08-28 20:58 UTC, merged

2020-08-29 02:15 UTC, lzutao commented on bors/src/git.rs
> +        if !path.is_file() {
This is [not really recommend way](https://doc.rust-lang.org/nightly/std/fs/struct.FileType.html#method.is_file) to check for a regular file. 
Use File::open and check its result to know if one can read/write to it.